name: Metrics
on:
  # Schedule updates (at 00:00 every day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rhshah
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_introduction: yes
          plugin_introduction_title: "Executive MBA Candidate & Senior Manager"
